# Generated by Django 6.1 on 2026-09-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wallettransaction',
            name='unique_wallet_transaction_reference',
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='reference',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
