# Generated by Django 6.1 on 2026-09-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_wallettransaction_unique_wallet_transaction_reference_and_more'),
    ]

    operations = []
