# Generated by Django 6.1 on 2026-09-27 12:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_wallettransaction_unique_wallet_transaction_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('phone_number', models.CharField(max_length=12)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('callback_token_hash', models.CharField(max_length=64, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('provider_receipt', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='initiated', max_length=12)),
                ('result_description', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='payments.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='payments_pa_status_f4857f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'idempotency_key'), name='unique_user_payment_idempotency_key'), models.CheckConstraint(condition=models.Q(('amount__gte', 1)), name='payment_attempt_amount_minimum')],
            },
        ),
    ]
