# Generated by Django 6.1 on 2026-10-10 20:23

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_payment_ledger(apps, schema_editor):
    LedgerEntry = apps.get_model('payments', 'LedgerEntry')
    Payment = apps.get_model('payments', 'Payment')
    Order = apps.get_model('shopping', 'Order')

    paid_order_ids = set()
    for payment in Payment.objects.filter(status='succeeded').iterator():
        if payment.amount <= 0:
            continue
        paid_order_ids.add(payment.order_id)
        LedgerEntry.objects.get_or_create(
            reference=f'legacy-payment:{payment.pk}:received',
            defaults={
                'order_id': payment.order_id,
                'payment_id': payment.pk,
                'user_id': payment.order.buyer_id,
                'entry_type': 'customer_payment',
                'amount': payment.amount,
                'currency': payment.currency,
                'metadata': {'source': 'migration'},
            },
        )

    for order in Order.objects.filter(payment_status='paid').exclude(pk__in=paid_order_ids).iterator():
        if order.amount_paid <= 0:
            continue
        LedgerEntry.objects.get_or_create(
            reference=f'legacy-order:{order.pk}:payment',
            defaults={
                'order_id': order.pk,
                'user_id': order.buyer_id,
                'entry_type': 'customer_payment',
                'amount': order.amount_paid,
                'currency': order.currency,
                'metadata': {'provider': order.payment_method, 'source': 'migration'},
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentattempt'),
        ('shopping', '0008_order_amount_paid_order_delivery_fee_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('customer_payment', 'Customer Payment Received'), ('delivery_fee', 'Delivery Fee Received'), ('seller_proceeds_hold', 'Seller Proceeds Held'), ('seller_proceeds_release', 'Seller Proceeds Released'), ('seller_proceeds_reversal', 'Seller Proceeds Reversed'), ('commission_hold', 'Commission Held'), ('commission_earned', 'Commission Earned'), ('commission_reversal', 'Commission Reversed'), ('refund_due', 'Refund Due'), ('refund_completed', 'Refund Completed')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='KES', max_length=3, validators=[django.core.validators.RegexValidator(message='Currency must be a three-letter uppercase code.', regex='^[A-Z]{3}$')])),
                ('reference', models.CharField(max_length=160, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='callback_token_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('order_total', 'Order Total'), ('delivery_fee', 'Delivery Fee'), ('delivery_balance', 'Pay on Delivery Balance')], default='order_total', max_length=24),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('receipt_number__gt', '')), fields=('provider', 'receipt_number'), name='unique_payment_provider_receipt'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='shopping.order'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['order', 'entry_type'], name='payments_le_order_i_da7b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['user', 'entry_type'], name='payments_le_user_id_abe077_idx'),
        ),
        migrations.RunPython(backfill_payment_ledger, migrations.RunPython.noop),
    ]
