# Generated by Django 6.1 on 2026-09-14 13:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(upload_to=core.models.service_image_upload_path, validators=[core.models.validate_image_upload]),
        ),
    ]
