# Generated by Django 6.1 on 2026-08-31 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='store',
            new_name='store_manag_status_a39e24_idx',
            old_name='store_manag_status_3d8c9e_idx',
        ),
    ]
