# Generated by Django 6.1 on 2026-09-14 13:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0003_store_address_store_business_type_store_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.store_banner_upload_path),
        ),
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.store_logo_upload_path),
        ),
        migrations.AddField(
            model_name='storekyc',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=core.models.kyc_document_upload_path),
        ),
        migrations.AddField(
            model_name='storekyc',
            name='document_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
