# Generated by Django 6.1 on 2026-09-14 13:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0004_store_banner_store_logo_storekyc_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='store',
            name='total_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='total_products',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='store',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.store_banner_upload_path, validators=[core.models.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.store_logo_upload_path, validators=[core.models.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='storekyc',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=core.models.kyc_document_upload_path, validators=[core.models.validate_document_upload]),
        ),
        migrations.AlterField(
            model_name='storekyc',
            name='document_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID'), ('business_registration', 'Business Registration'), ('tax_certificate', 'Tax Certificate'), ('passport', 'Passport')], default='', max_length=50),
        ),
    ]
