# Generated by Django 6.1 on 2026-08-29 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='product_man_status_caffb3_idx',
            old_name='product_man_status_8a1a4e_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='product_man_store_i_c9b5ab_idx',
            old_name='product_man_store_i_4fba10_idx',
        ),
    ]
