# Generated by Django 6.1 on 2026-09-14 13:22

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_tag_category_product_category_product_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=core.models.product_image_upload_path, validators=[core.models.validate_image_upload]),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sku_suffix', models.CharField(max_length=40)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product_management.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'sku_suffix'), name='unique_variant_sku_suffix_per_product')],
            },
        ),
    ]
