# Generated by Django 6.1 on 2026-09-10 10:50

from django.db import migrations, models


def copy_existing_created_timestamps(apps, schema_editor):
    BlacklistedToken = apps.get_model('authapp', 'BlacklistedToken')
    User = apps.get_model('authapp', 'User')

    BlacklistedToken.objects.filter(created_at__isnull=True).update(created_at=models.F('blacklisted_at'))
    User.objects.filter(created_at__isnull=True).update(created_at=models.F('date_joined'))


def reverse_copy_existing_created_timestamps(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistedtoken',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='blacklistedtoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(copy_existing_created_timestamps, reverse_copy_existing_created_timestamps),
        migrations.AlterField(
            model_name='blacklistedtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
