# Generated by Django 6.1 on 2026-09-14 13:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_blacklistedtoken_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.avatar_upload_path),
        ),
    ]
