# Generated by Django 6.1 on 2026-09-22 10:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_management', '0005_remove_product_variants'),
        ('service_management', '0003_booking'),
        ('store_management', '0005_store_average_rating_store_total_orders_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, default='')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product_management.product')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='service_management.service')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store_management.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='reviews_rev_product_d800fc_idx'), models.Index(fields=['service', '-created_at'], name='reviews_rev_service_0d3aeb_idx'), models.Index(fields=['store', '-created_at'], name='reviews_rev_store_i_2b8862_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('reviewer', 'product'), name='one_review_per_product'), models.UniqueConstraint(condition=models.Q(('service__isnull', False)), fields=('reviewer', 'service'), name='one_review_per_service'), models.UniqueConstraint(condition=models.Q(('store__isnull', False)), fields=('reviewer', 'store'), name='one_review_per_store')],
            },
        ),
    ]
