# Generated by Django 6.1 on 2026-10-10 20:23

import django.db.models.deletion
import uuid
from collections import defaultdict
from decimal import Decimal, ROUND_HALF_UP
from django.conf import settings
from django.db import migrations, models


MONEY = Decimal('0.01')
COMMISSION_RATE = Decimal('0.1000')


def backfill_order_financials(apps, schema_editor):
    Order = apps.get_model('shopping', 'Order')
    OrderItem = apps.get_model('shopping', 'OrderItem')
    OrderFulfillment = apps.get_model('shopping', 'OrderFulfillment')

    for order in Order.objects.all().iterator():
        items = list(
            OrderItem.objects.filter(order_id=order.pk).select_related('product__store')
        )
        grouped = defaultdict(list)
        item_subtotal = Decimal('0.00')

        for item in items:
            line_total = (item.price_at_purchase * item.quantity).quantize(MONEY)
            commission = (line_total * COMMISSION_RATE).quantize(MONEY, rounding=ROUND_HALF_UP)
            item.commission_rate = COMMISSION_RATE
            item.commission_amount = commission
            item.seller_proceeds = line_total - commission
            item.save(update_fields=['commission_rate', 'commission_amount', 'seller_proceeds'])
            item_subtotal += line_total
            if item.seller_id:
                grouped[item.seller_id].append(item)

        order.item_subtotal = item_subtotal.quantize(MONEY)
        order.payment_option = 'pay_now'
        order.amount_paid = order.total_amount if order.payment_status == 'paid' else Decimal('0.00')
        # Legacy checkout never collected the seller-entered shipping estimate.
        order.delivery_fee_paid = False
        order.save(update_fields=[
            'item_subtotal', 'payment_option', 'amount_paid', 'delivery_fee_paid',
        ])

        for seller_id, seller_items in grouped.items():
            seller_subtotal = sum(
                (item.price_at_purchase * item.quantity for item in seller_items),
                Decimal('0.00'),
            ).quantize(MONEY)
            seller_commission = sum(
                (item.commission_amount for item in seller_items),
                Decimal('0.00'),
            ).quantize(MONEY)
            origin_city = ''
            first_product = seller_items[0].product
            if first_product is not None and first_product.store_id:
                origin_city = first_product.store.city or ''
            OrderFulfillment.objects.get_or_create(
                order_id=order.pk,
                seller_id=seller_id,
                defaults={
                    'status': order.status,
                    'item_subtotal': seller_subtotal,
                    'commission_amount': seller_commission,
                    'seller_proceeds': seller_subtotal - seller_commission,
                    'shipping_cost': Decimal('0.00'),
                    'actual_weight_kg': Decimal(sum(item.quantity for item in seller_items)),
                    'volumetric_weight_kg': Decimal('0.000'),
                    'chargeable_weight_kg': Decimal(sum(item.quantity for item in seller_items)),
                    'origin_city': origin_city,
                    'origin_region': '',
                    'destination_city': order.shipping_city,
                    'destination_region': '',
                    'courier_name': order.courier_name,
                    'tracking_number': order.tracking_number,
                    'shipped_at': order.shipped_at,
                    'settlement_status': 'pending',
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_order_courier_name_order_shipped_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='item_subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('pay_now', 'Pay Now'), ('pay_on_delivery', 'Pay on Delivery')], default='pay_now', max_length=24),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='commission_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1000'), max_digits=5),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller_proceeds',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderFulfillment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('item_subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('seller_proceeds', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_weight_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('volumetric_weight_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('chargeable_weight_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('origin_city', models.CharField(max_length=100)),
                ('origin_region', models.CharField(max_length=32)),
                ('destination_city', models.CharField(max_length=100)),
                ('destination_region', models.CharField(max_length=32)),
                ('courier_name', models.CharField(blank=True, default='', max_length=100)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=100)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('settlement_status', models.CharField(choices=[('pending', 'Pending Payment'), ('held', 'Held Until Delivery'), ('released', 'Released to Seller'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='shopping.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_fulfillments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['seller', 'status'], name='shopping_or_seller__eae944_idx'), models.Index(fields=['order', 'status'], name='shopping_or_order_i_b2b413_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'seller'), name='unique_order_seller_fulfillment')],
            },
        ),
        migrations.RunPython(backfill_order_financials, migrations.RunPython.noop),
    ]
